### ISSUE TITLE
計算機程式分組期末專案題目討論 - 同時學習如何開發網際與視窗程式

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2018#18]
# 程式技術
以 [p37](https://drive.google.com/file/d/1Pkkjg8RX3pkZkjWEBlQBggw11u5YSn5i/view?usp=sharing) 或 [p37_adv](https://drive.google.com/file/d/1_lisI3UVmYAEtM3wiSZ96QxDYrb0uV7n/view?usp=sharing) 可攜程式開發系統, 為主要工具. 前者解開放入隨身碟約佔 1 GB, 主要提供 Python 3.7.0.1, SciTE, Leo Editor, Eric6, PyQt5 與 Flask 等系統, 而後者解開壓縮檔後約佔 15 GB, 除上述工具外, 還包括 [MSYS2](https://www.msys2.org/) 與 [Make](https://en.wikipedia.org/wiki/Make_(software)#Makefile) 開發環境.

# 分組專案題目

## 改進 CMSimfly 網際(機械設計)內容管理系統
先充分了解 CMSimfly 的程式架構, 將各功能改寫為獨立模組 (Modules) 或程式庫 (Libraries) 或套件 (Packages)

Python 模組 - 為一個 .py 的程式檔案, 可以由其他 Python 程式中 import 後引用.
Python 程式庫 - 為一個靜態程式庫 .a 或者動態程式庫 .pyd 檔案, 可以由其他 Python 程式中 import 後引用.
Python 套件 - 由許多程式模組 (即 .py 檔案) 所組成.

http://www.codedata.com.tw/python/python-tutorial-the-2nd-class-3-function-module-class-package

從了解 CMSimfly 中的 parse_content() 開始:
[cmsimfly_parse_ex.zip](https://github.com/mdecourse/cp2018/files/2475367/cmsimfly_parse_ex.zip)

將現有的 [tinymce4](https://github.com/tinymce/tinymce) html 編輯器改為 markdown 編輯器, 以利協同編輯時的資料合併.

https://github.com/joemccann/dillinger or https://github.com/benweet/stackedit

## 利用網際行事曆管理設計流程

https://mdecdlab.github.io/lab-booking-cdlab/doc/
http://tsmccenter.ntu.edu.tw/06/01.php
https://github.com/kkarimi/flask-fullcalendar
https://github.com/TheCraftsmen/fullcalendar-flask
https://gist.github.com/Nikola-K/37e134c741127380f5d6
https://github.com/ParkMinKyu/scheduler

## V-rep Python remote API

http://www.coppeliarobotics.com/helpFiles/en/remoteApiFunctionsPython.htm
https://github.com/Troxid/vrep-api-python
https://github.com/rezaxdi/vrep-volleyball
https://github.com/luwood/MO810-vrep-python
https://github.com/BlazingFire/ObstacleAvoidanceWithQ-Learning

Lua: https://github.com/RuslanGainanov/robot-motion

C++ and [CMake](https://cmake.org/): https://github.com/luwood/MO810-vrep-cpp ([ref](https://github.com/tudelft3d/masbcpp/wiki/Building-on-Windows-with-CMake-and-MinGW))

## PyQt5

https://github.com/KmolYuan/cam-profile
https://github.com/KmolYuan/Pyslvs-PyQt5

**Comment by mdecourse** [comment]
# PyQt5 與 Python3 專案範例

https://github.com/JLuebben/Floppy
https://github.com/mfitzp/15-minute-apps

# 算數計算機:

    #!/usr/bin/env python


    #############################################################################
    ##
    ## Copyright (C) 2013 Riverbank Computing Limited.
    ## Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
    ## All rights reserved.
    ##
    ## This file is part of the examples of PyQt.
    ##
    ## $QT_BEGIN_LICENSE:BSD$
    ## You may use this file under the terms of the BSD license as follows:
    ##
    ## "Redistribution and use in source and binary forms, with or without
    ## modification, are permitted provided that the following conditions are
    ## met:
    ##   * Redistributions of source code must retain the above copyright
    ##     notice, this list of conditions and the following disclaimer.
    ##   * Redistributions in binary form must reproduce the above copyright
    ##     notice, this list of conditions and the following disclaimer in
    ##     the documentation and/or other materials provided with the
    ##     distribution.
    ##   * Neither the name of Nokia Corporation and its Subsidiary(-ies) nor
    ##     the names of its contributors may be used to endorse or promote
    ##     products derived from this software without specific prior written
    ##     permission.
    ##
    ## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    ## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    ## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
    ## A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
    ## OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    ## SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
    ## LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    ## DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
    ## THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    ## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    ## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
    ## $QT_END_LICENSE$
    ##
    #############################################################################


    import math

    from PyQt5.QtCore import Qt
    from PyQt5.QtWidgets import (QApplication, QGridLayout, QLayout, QLineEdit,
            QSizePolicy, QToolButton, QWidget)


    class Button(QToolButton):
        def __init__(self, text, parent=None):
            super(Button, self).__init__(parent)

            self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
            self.setText(text)

        def sizeHint(self):
            size = super(Button, self).sizeHint()
            size.setHeight(size.height() + 20)
            size.setWidth(max(size.width(), size.height()))
            return size


    class Calculator(QWidget):
        NumDigitButtons = 10
        
        def __init__(self, parent=None):
            super(Calculator, self).__init__(parent)

            self.pendingAdditiveOperator = ''
            self.pendingMultiplicativeOperator = ''

            self.sumInMemory = 0.0
            self.sumSoFar = 0.0
            self.factorSoFar = 0.0
            self.waitingForOperand = True

            self.display = QLineEdit('0')
            self.display.setReadOnly(True)
            self.display.setAlignment(Qt.AlignRight)
            self.display.setMaxLength(15)

            font = self.display.font()
            font.setPointSize(font.pointSize() + 8)
            self.display.setFont(font)

            self.digitButtons = []
            
            for i in range(Calculator.NumDigitButtons):
                self.digitButtons.append(self.createButton(str(i),
                        self.digitClicked))

            self.pointButton = self.createButton(".", self.pointClicked)
            self.changeSignButton = self.createButton(u"\N{PLUS-MINUS SIGN}",
                    self.changeSignClicked)

            self.backspaceButton = self.createButton("Backspace",
                    self.backspaceClicked)
            self.clearButton = self.createButton("Clear", self.clear)
            self.clearAllButton = self.createButton("Clear All", self.clearAll)

            self.clearMemoryButton = self.createButton("MC", self.clearMemory)
            self.readMemoryButton = self.createButton("MR", self.readMemory)
            self.setMemoryButton = self.createButton("MS", self.setMemory)
            self.addToMemoryButton = self.createButton("M+", self.addToMemory)

            self.divisionButton = self.createButton(u"\N{DIVISION SIGN}",
                    self.multiplicativeOperatorClicked)
            self.timesButton = self.createButton(u"\N{MULTIPLICATION SIGN}",
                    self.multiplicativeOperatorClicked)
            self.minusButton = self.createButton("-", self.additiveOperatorClicked)
            self.plusButton = self.createButton("+", self.additiveOperatorClicked)

            self.squareRootButton = self.createButton("Sqrt",
                    self.unaryOperatorClicked)
            self.powerButton = self.createButton(u"x\N{SUPERSCRIPT TWO}",
                    self.unaryOperatorClicked)
            self.reciprocalButton = self.createButton("1/x",
                    self.unaryOperatorClicked)
            self.equalButton = self.createButton("=", self.equalClicked)

            mainLayout = QGridLayout()
            mainLayout.setSizeConstraint(QLayout.SetFixedSize)

            mainLayout.addWidget(self.display, 0, 0, 1, 6)
            mainLayout.addWidget(self.backspaceButton, 1, 0, 1, 2)
            mainLayout.addWidget(self.clearButton, 1, 2, 1, 2)
            mainLayout.addWidget(self.clearAllButton, 1, 4, 1, 2)

            mainLayout.addWidget(self.clearMemoryButton, 2, 0)
            mainLayout.addWidget(self.readMemoryButton, 3, 0)
            mainLayout.addWidget(self.setMemoryButton, 4, 0)
            mainLayout.addWidget(self.addToMemoryButton, 5, 0)

            for i in range(1, Calculator.NumDigitButtons):
                row = ((9 - i) / 3) + 2
                column = ((i - 1) % 3) + 1
                mainLayout.addWidget(self.digitButtons[i], row, column)

            mainLayout.addWidget(self.digitButtons[0], 5, 1)
            mainLayout.addWidget(self.pointButton, 5, 2)
            mainLayout.addWidget(self.changeSignButton, 5, 3)

            mainLayout.addWidget(self.divisionButton, 2, 4)
            mainLayout.addWidget(self.timesButton, 3, 4)
            mainLayout.addWidget(self.minusButton, 4, 4)
            mainLayout.addWidget(self.plusButton, 5, 4)

            mainLayout.addWidget(self.squareRootButton, 2, 5)
            mainLayout.addWidget(self.powerButton, 3, 5)
            mainLayout.addWidget(self.reciprocalButton, 4, 5)
            mainLayout.addWidget(self.equalButton, 5, 5)
            self.setLayout(mainLayout)

            self.setWindowTitle("Calculator")

        def digitClicked(self):
            clickedButton = self.sender()
            digitValue = int(clickedButton.text())

            if self.display.text() == '0' and digitValue == 0.0:
                return

            if self.waitingForOperand:
                self.display.clear()
                self.waitingForOperand = False

            self.display.setText(self.display.text() + str(digitValue))

        def unaryOperatorClicked(self):
            clickedButton = self.sender()
            clickedOperator = clickedButton.text()
            operand = float(self.display.text())

            if clickedOperator == "Sqrt":
                if operand < 0.0:
                    self.abortOperation()
                    return

                result = math.sqrt(operand)
            elif clickedOperator == u"x\N{SUPERSCRIPT TWO}":
                result = math.pow(operand, 2.0)
            elif clickedOperator == "1/x":
                if operand == 0.0:
                    self.abortOperation()
                    return

                result = 1.0 / operand

            self.display.setText(str(result))
            self.waitingForOperand = True

        def additiveOperatorClicked(self):
            clickedButton = self.sender()
            clickedOperator = clickedButton.text()
            operand = float(self.display.text())

            if self.pendingMultiplicativeOperator:
                if not self.calculate(operand, self.pendingMultiplicativeOperator):
                    self.abortOperation()
                    return

                self.display.setText(str(self.factorSoFar))
                operand = self.factorSoFar
                self.factorSoFar = 0.0
                self.pendingMultiplicativeOperator = ''

            if self.pendingAdditiveOperator:
                if not self.calculate(operand, self.pendingAdditiveOperator):
                    self.abortOperation()
                    return

                self.display.setText(str(self.sumSoFar))
            else:
                self.sumSoFar = operand

            self.pendingAdditiveOperator = clickedOperator
            self.waitingForOperand = True

        def multiplicativeOperatorClicked(self):
            clickedButton = self.sender()
            clickedOperator = clickedButton.text()
            operand = float(self.display.text())

            if self.pendingMultiplicativeOperator:
                if not self.calculate(operand, self.pendingMultiplicativeOperator):
                    self.abortOperation()
                    return

                self.display.setText(str(self.factorSoFar))
            else:
                self.factorSoFar = operand

            self.pendingMultiplicativeOperator = clickedOperator
            self.waitingForOperand = True

        def equalClicked(self):
            operand = float(self.display.text())

            if self.pendingMultiplicativeOperator:
                if not self.calculate(operand, self.pendingMultiplicativeOperator):
                    self.abortOperation()
                    return

                operand = self.factorSoFar
                self.factorSoFar = 0.0
                self.pendingMultiplicativeOperator = ''

            if self.pendingAdditiveOperator:
                if not self.calculate(operand, self.pendingAdditiveOperator):
                    self.abortOperation()
                    return

                self.pendingAdditiveOperator = ''
            else:
                self.sumSoFar = operand

            self.display.setText(str(self.sumSoFar))
            self.sumSoFar = 0.0
            self.waitingForOperand = True

        def pointClicked(self):
            if self.waitingForOperand:
                self.display.setText('0')

            if "." not in self.display.text():
                self.display.setText(self.display.text() + ".")

            self.waitingForOperand = False

        def changeSignClicked(self):
            text = self.display.text()
            value = float(text)

            if value > 0.0:
                text = "-" + text
            elif value < 0.0:
                text = text[1:]

            self.display.setText(text)

        def backspaceClicked(self):
            if self.waitingForOperand:
                return

            text = self.display.text()[:-1]
            if not text:
                text = '0'
                self.waitingForOperand = True

            self.display.setText(text)

        def clear(self):
            if self.waitingForOperand:
                return

            self.display.setText('0')
            self.waitingForOperand = True

        def clearAll(self):
            self.sumSoFar = 0.0
            self.factorSoFar = 0.0
            self.pendingAdditiveOperator = ''
            self.pendingMultiplicativeOperator = ''
            self.display.setText('0')
            self.waitingForOperand = True

        def clearMemory(self):
            self.sumInMemory = 0.0

        def readMemory(self):
            self.display.setText(str(self.sumInMemory))
            self.waitingForOperand = True

        def setMemory(self):
            self.equalClicked()
            self.sumInMemory = float(self.display.text())

        def addToMemory(self):
            self.equalClicked()
            self.sumInMemory += float(self.display.text())

        def createButton(self, text, member):
            button = Button(text)
            button.clicked.connect(member)
            return button

        def abortOperation(self):
            self.clearAll()
            self.display.setText("####")

        def calculate(self, rightOperand, pendingOperator):
            if pendingOperator == "+":
                self.sumSoFar += rightOperand
            elif pendingOperator == "-":
                self.sumSoFar -= rightOperand
            elif pendingOperator == u"\N{MULTIPLICATION SIGN}":
                self.factorSoFar *= rightOperand
            elif pendingOperator == u"\N{DIVISION SIGN}":
                if rightOperand == 0.0:
                    return False

                self.factorSoFar /= rightOperand

            return True


    if __name__ == '__main__':

        import sys

        app = QApplication(sys.argv)
        calc = Calculator()
        calc.show()
        sys.exit(app.exec_())

**Comment by KmolYuan** [comment]
##  Pure Python outliner

純 Python 大綱編輯器 kmol editor 的功能擴充。客製化 Leo editor 的延伸工具，由樹狀結構儲存文本內容，用來編輯層次性的文本檔案。

技術：

+ YAML
+ Markdown
+ HTML
+ Regular expression
+ PyQt 和 QSicntilla。
+ 執行緒管理。

現有功能：

+ Markdown 解析器。
+ 拼字檢查。
+ 單詞重構。
+ 樹狀表示式及 Hash code dataset。 
+ 內文關鍵字亮顯。
+ 非英文支援（採用字節計算）。

未達成功能：

+ 跨節點搜尋。
+ Google 翻譯。
+ Latax math 預覽。
+ Reveal.js 支援。
+ 樣板式專案編輯（CMSimfly）。
+ 自動解析目錄。
