### ISSUE TITLE
在 CMSimfly 新增 Highlighter

### ISSUE THREAD

**Issue by KmolYuan** [mdecourse/cp2018#21]
目錄 `/static/syntaxhighlighter/` 中有 [syntaxhighlighter] 的 Java Script 腳本，但是 generate pages 時不會載入，是因為 `syntaxhighlight` 和 `syntaxhighlight2` 函式中不會載入相應的腳本。

https://github.com/mdecourse/cp2018/blob/377c7da3663af22de1ded3f11c7b72563395ac18/flaskapp.py#L2021-L2035

https://github.com/mdecourse/cp2018/blob/377c7da3663af22de1ded3f11c7b72563395ac18/flaskapp.py#L2077-L2091

例如插入 `shBrushBash.js` 可以使用 Bash / Shell / cmd 的 highlighter。

[syntaxhighlighter]: https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Brushes-and-Themes

**Comment by mdecourse** [comment]
請再測試看看, 已經加入幾個常用程式的[高亮顯示頁面範例](https://chiamingyen.github.io/cmsimfly/content/Java%20%E7%A8%8B%E5%BC%8F%E7%A2%BC.html)

另外, 也請注意目前[已知的 CMSimfly 程式錯誤](https://chiamingyen.github.io/cmsimfly/content/%E5%B7%B2%E7%9F%A5%E9%8C%AF%E8%AA%A4.html)
