### ISSUE TITLE
老師我想要在 CMSimfly 上加入 Brython

### ISSUE THREAD

**Issue by s40723136** [mdecourse/cp2018#24]
老師我嘗試複製了一些模組和複製了部分的網頁原始碼，但是 Ace 顯示不出來。

https://github.com/mdecp2018/site-s40723136/blob/gh-pages/content/python.html#L41-L46

+ `ace/`
+ `py/`
+ `brython.js`
+ `brython_stdlib.js`

<https://mdecp2018.github.io/site-s40723136/content/python.html>

**Comment by mdecourse** [comment]
已經針對錯誤訊息處理, 目前頁面已經可以執行 Brython:
https://mdecp2018.github.io/site-s40723136/content/python.html

第一次修正時, 並未發現你的 CMSimfly 為開學時的舊版, 過程中已經更新許多地方, 其中包括讓使用者可以將 Brython 或 fengari-web.js 帶在各自的頁面, 而非從原始系統啟動就在各頁面中導入.

https://github.com/mdecp2018/site-s40723136/commit/7134349cfbdce392eb9fca6dc06d0f48aad1b5bb

移除 CMSimfly 啟動時帶出各 js 連結的設定: https://github.com/mdecp2018/site-s40723136/commit/03e8d28de9f05473ae6acb031761132440fd238a

而第二次修正時, 又發現你的 generate_pages 並未配合上述將 js 放在頁面動態編輯時採用絕對目錄, 而靜態頁面則有必須轉為相對目錄, 最後終於在第三次修正時, 將 get_page 與 get_page2

另外, 目前使用 Brython 3.7.0, 模組的設定必須放在 "/static/", 並且加入啟動網際 Ace 編輯用的 ace.py 與 beditor.py, 讓 Brython 程式可以正確啟動.
