### ISSUE TITLE
Week11 - Github Pages 靜態網站與 Heroku 動態網站自動同步

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2018#30]
# 示範 Github 倉儲
https://github.com/mdecp2018/finalproject-bgx
# 靜態網站
https://mdecp2018.github.io/finalproject-bgx 
# 同步動態網站
http://cp2018-bgx.herokuapp.com

**Comment by scrum-3** [comment]
https://cadp2018-bgx.herokuapp.com/ 
https://github.com/mdecadp2018/finalproject-bgx

https://cp2018-bgx-m1.herokuapp.com 
https://github.com/scrum-1/finalproject-bgx
