### ISSUE TITLE
Week1 - 指定學員獨立作業

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2018#6]
# W1-W9 各學員獨立作業

根據[分組協同流程](https://github.com/mdecourse/cp2018/wiki/2018-Fall--%E5%88%86%E7%B5%84%E5%8D%94%E5%90%8C%E6%B5%81%E7%A8%8B)中學員須知準備隨身碟、耳機、麥克風與紙本筆記

各學員利用學校配發之 email 申請 github 帳號, 以 s 加上學號作為帳號.

[2018cp1b 修課學員學號單](https://osa.nfu.edu.tw/query/studlist.php?selyr=1071&seqno=0784): 
[2018cp1b.txt](https://github.com/mdecourse/cp2018/files/2373018/2018cp1b.txt)

[2018cp1a 修課學員學號單](https://osa.nfu.edu.tw/query/studlist.php?selyr=1071&seqno=0770): 
[2018cp1a.txt](https://github.com/mdecourse/cp2018/files/2373021/2018cp1a.txt)

[2018cpve1a 修課學員學號單](https://osa.nfu.edu.tw/query/studlist.php?selyr=1071&seqno=7215):
[2018cpve1a.txt](https://github.com/mdecourse/cp2018/files/2373031/2018cpve1a.txt)

所有課程問題, 均在各週的對應 [issues](https://github.com/mdecourse/cadp2018/issues) 中, 利用學員帳號登入 github 後, 以 comment 方式提出.

請機械設計工程系各班學員登入 Github 帳號後, 領取必須在期中考週前完成的期中作業: https://classroom.github.com/a/wlLbt5TQ 

請車輛工程系各班學員登入 Github 帳號後, 領取必須在期中考週前完成的期中作業: 
https://classroom.github.com/a/YAYj6qcb

期中作業原始內容取自: [2018fall](https://github.com/mdecourse/2018fall), [示範網站](https://cpgx.kmol.info), 各學員期中成績以每週操作影片、[CMSimfly](https://github.com/chiamingyen/cmsimfly)、[reveal](https://revealjs.com/#/) 簡報、[pelican](https://blog.getpelican.com/) 網誌與倉儲歷程記錄作為自評依據.

實習指定內容 Python 程式簡介: 

### 各學員必須在 W9 前, 自行掌握進度, 每週拍攝操作實習影片, 將教材內容與使用心得放入個人的網站、簡報與網誌中.

http://mde.tw/cp2018/content/Python.html

# 專案課程內容

[CMSimfly](https://github.com/chiamingyen/cmsimfly) - 網際內容管理系統 ([Flask](http://flask.pocoo.org/))

[Pyslvs](https://github.com/KmolYuan/Pyslvs-PyQt5) - 平面機構模擬與合成系統 ([PyQt5](https://www.riverbankcomputing.com/software/pyqt/download5))

# W10-W18 分組課程專題

六人一組, 選擇一個分組程式主題, 各組依序領取期末專題原始倉儲 (內容取自: [2018fall](https://github.com/mdecourse/2018fall)),  各組員必須以協同方式在期末考週前完成分組專案計畫.

# W1 教學影片

根據 [Github Pages](https://pages.github.com/) 說明, 建立個人課程網頁 學號.github.io
git clone https://github.com/mdecourse/2018fall 至近端, 以 scrum-2 帳號錄製教學影片, 示範如何管理 [CMSimfly](https://github.com/chiamingyen/cmsimfly) 靜態網頁,  如何編輯 [reveal](https://revealjs.com/#/) 簡報內容, 如何建立 [pelican](https://blog.getpelican.com/) 網誌 (近端檢視, 遠端加入 [disqus](https://help.disqus.com/) 討論區連結).

http://mde.tw/cp2018 內容導引

**Comment by mdecourse** [comment]
# Github Education

在 2014 年 2 月,  Github [推出](https://blog.github.com/2014-02-10-github-goes-to-school/) 陽春的 Github Education 服務.

當時提供:

  * Free Micro accounts for students and teachers
  * Free GitHub organization accounts for classroom use
  * A 25% discount for all other educational use cases

我們不為所動.

2018 年 6 月微軟以 76 億美元購入 Github 後, https://education.github.com/ 持續加碼, 對教育單位釋出:

  * Free access to GitHub Enterprise or Business Cloud for all of your technical departments
  * Teacher training to master Git and GitHub with our Campus Advisors program
  * Automated access to premium GitHub Education features, like the GitHub Student Developer Pack
  * Exclusive access to new features, and GitHub Education-specific swag

這一次, 整個大學都能夠採用業界模式上課, 我們將要全盤接受.

已經建立了 https://github.com/kmolnfu 準備在熟悉使用流程之後納入[計算機程式](https://mdecourse.github.io/cp2018/)、[電腦輔助設計實習](https://mdecourse.github.io/cadp2018/)、網際內容管理與協同產品設計實習課程中.

# Assignment 指定

https://github.com/kmolnfu/personal-github-page-site-scrum-1 是第一個以 scrum-1 測試用戶接受作業所得的連結.

其中:

指定作業: https://classroom.github.com/classrooms/43160048-kmolab-nfu-taiwan/assignments/personal-github-page-site

作業邀請連結: https://classroom.github.com/a/jV6Mag7J

而前提必須該作業設定中, 將修課學員的帳號, 以 csv 檔案上傳, 然後各學員從作業邀請連結取得該作業的倉儲內容.

以上述範例作業中, 指定的起始內容為位於 gh-pages 的 https://github.com/mdecourse/2018fall, 則當 scrum-1 取得指定作業倉儲時, 

位於 kmolnfu 課堂中的 https://github.com/kmolnfu/personal-github-page-site-scrum-1 會被指定給 scrum-1, 當使用者接受指定作業後, 登入 github 後至 https://github.com/ 就可在左方 Repositories 區見到指定作業倉儲的連結.

由於該倉儲使用 gh-pages 分支作為 Github Pages 網站的內容, 因此各學員在推送資料版本時, 必須以 gh-pages 分支的內容為主.

**Comment by chiamingyen** [comment]
# 計算機程式 Github 課程教室

https://classroom.github.com/classrooms/43208929-mdecp2018

**Comment by mdecourse** [comment]
# mdecp2018 學員網誌 disqus 設定

mdecp2018 各學員取得期中作業倉儲後, 若要啟動 Pelican Blog 中的 disqus, 可以修改 config/pelican.leo 中, "Pelican 設定"節點下方的 @edit publishconf.py 內容, 指定 DISQUS_SITENAME:

DISQUS_SITENAME = "mdecp2018"

![zoomit64_2018-09-15_09-28-04](https://user-images.githubusercontent.com/20835445/45580979-db2e9300-b8c9-11e8-925d-fe8bb0d04878.png)

vecp2018 各班學員則可將 DISQUS_SITENAME 設為 "vecp2018", 即將

作業倉儲中 config/pelican.leo 檔案中的 "Pelican 設定"節點下方的 @edit publishconf.py 內容, 指定 DISQUS_SITENAME:

DISQUS_SITENAME = "vecp2018"

![zoomit64_2018-09-15_09-27-31](https://user-images.githubusercontent.com/20835445/45580974-cc47e080-b8c9-11e8-8ef5-42a590069ef4.png)

**Comment by mdecourse** [comment]
# 假如您使用 32 位元的操作系統
計算機程式課程所提供的 [P37](https://drive.google.com/file/d/1DWtyoUhl8CycKJ8uulB3viRXE39KqpE1/view?usp=sharing) 可攜程式系統, 都是 64 位元 Windows 操作系統相容的工具, 可以在 Windows 7 或 Windows 10 64 位元操作系統中使用.

假如您的 Windows 7 仍為 32 位元系統, 可以下載 [P37_32](https://mde1a1.kmol.info/2017fall/raw/p37_32.7z?name=c272a694f98180f8d1272b43f7d7b4fdd8f7f550) 可攜版本, 相較於 64 位元版本, 32 位元版本缺少 [Eric6](https://eric-ide.python-projects.org/eric-download.html) IDE 的支援.

[Eric6](https://eric-ide.python-projects.org/eric-download.html) 是計算機程式課程用來開發 PyQt5 視窗程式所使用的整合開發環境 (Integrated Development Environment, IDE).
